# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: devopsi   #app:n nimi

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  test:
    runs-on: ubuntu-latest                     #testi omana jobina. testataan ennen buildia ja julkaisua
    

    steps:
      - uses: actions/checkout@v1              #tarkistaa koodin
        

      - name: npm install                      #asentaa riippuvuudet
        run: npm install
        

      - name: Run unit tests                                        #yksikkötestit
        run: npm test -- --watch=false --browsers=ChromeHeadless    #estää chromea käynnistymästä
        
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |                                                      #tässä asennetaan ja buildataan projekti
          npm install
          npm run build

          
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: dist/angular-example-app/

  build-docker:                                                    #buildataan docker
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master                      #lataa artefaktin
        with:
          name: webpack artifacts
          path: dist/angular-example-app/
      - name: Set up Docker Buildx                                   #lataa ja asentaa Buildx työkalun
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry                # rakentaa docker kuvan ja puskee docker kuvan konttirekisteriin
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:                                                                  
    runs-on: ubuntu-latest

    needs: build-docker

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App                                          #deployataan projekti azureen
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}          # secretit
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
